# Generated by Django 3.1.7 on 2022-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Ispending'), (2, 'Inprogress'), (3, 'Nottaken'), (4, 'Completed')], default=1)),
                ('isrush', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('specifications', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('spiel', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
