# Generated by Django 4.0.3 on 2022-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0002_alter_jof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jof',
            name='status',
            field=models.IntegerField(choices=[(1, 'Is Pending'), (2, 'In Progress'), (3, 'Not Taken'), (4, 'Is Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='jof',
            name='type',
            field=models.IntegerField(choices=[(1, 'Music/Audio'), (2, 'Video'), (3, 'Picture'), (4, 'GIF'), (5, 'PDF'), (6, 'Word Document'), (7, 'Other')], default=7),
        ),
    ]
