# Generated by Django 4.0.3 on 2022-04-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0003_alter_jof_status_alter_jof_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jof',
            old_name='specifications',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='jof',
            name='pegs',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
