# Generated by Django 3.1.7 on 2022-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0004_rename_specifications_jof_summary_jof_pegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jof',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
