# Generated by Django 3.1.7 on 2022-04-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20220428_1328'),
        ('joffeedapp', '0005_auto_20220428_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='jof',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Artist', to='loginapp.account'),
        ),
        migrations.AddField(
            model_name='jof',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='loginapp.account'),
        ),
    ]
