# Generated by Django 4.0.3 on 2022-04-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_alter_account_id_alter_department_id'),
        ('joffeedapp', '0007_auto_20220428_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='jof',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='loginapp.department'),
        ),
        migrations.AlterField(
            model_name='jof',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
