# Generated by Django 4.0.3 on 2022-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0010_auto_20220511_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jof',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jof',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jof',
            name='spiel',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jof',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
    ]
