# Generated by Django 4.0.3 on 2022-05-11 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0011_alter_jof_description_alter_jof_id_alter_jof_spiel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('source', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='joffeedapp.jof')),
            ],
        ),
    ]
