# Generated by Django 4.0.3 on 2022-05-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_alter_account_id_alter_department_id'),
        ('joffeedapp', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='source',
            new_name='jof',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='source',
            new_name='jof',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loginapp.account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
