# Generated by Django 3.1.7 on 2022-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0015_auto_20220515_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='dnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='spiel',
            field=models.CharField(default='', max_length=500),
        ),
    ]
