# Generated by Django 3.1.7 on 2022-05-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0016_auto_20220515_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='jof',
        ),
        migrations.AddField(
            model_name='comment',
            name='draft',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='joffeedapp.draft'),
        ),
    ]
