# Generated by Django 4.0.3 on 2022-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0018_alter_comment_id_alter_draft_id_alter_jof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='spiel',
            field=models.CharField(default='', max_length=2200),
        ),
    ]
