# Generated by Django 4.0.3 on 2022-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0019_alter_draft_spiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jof',
            name='spiel',
            field=models.CharField(default='', max_length=2200),
        ),
    ]
