# Generated by Django 3.1.7 on 2022-05-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joffeedapp', '0020_alter_jof_spiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='spiel',
            field=models.TextField(default='', max_length=2200),
        ),
        migrations.AlterField(
            model_name='jof',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jof',
            name='spiel',
            field=models.TextField(default='', max_length=2200),
        ),
        migrations.AlterField(
            model_name='jof',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
    ]
