# Generated by Django 3.1.7 on 2022-03-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='DepartmentModel',
            new_name='Department',
        ),
    ]
